version: '2.1'

services:
  app:
    build: .
    environment:
      INSERTION_QUEUE: insertion.queue
      VALIDATION_QUEUE: validation.queue
      NUMBER_OF_VALIDATION_CONSUMERS: 1
      RESPONSE_EXCHANGE: response.exchange
      RESPONSE_ROUTING_KEY: response.routing.key
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: /
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      JDBC_URL: jdbc:mysql://mysql:3306/axr_challenge?user=root&password=secret
      DEAD_LETTER_QUEUE: deadletter.queue
    links:
      - mysql:mysql
      - rabbitmq:rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: axr_challenge
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 15s
      retries: 30
  rabbitmq:
    image: rabbitmq:3.6-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "/usr/lib/rabbitmq/lib/rabbitmq_server-3.6.16/sbin/./rabbitmqctl", "status" ]
      interval: 5s
      timeout: 15s
      retries: 30